### ISSUE TITLE
'contact.html' page section height bug

### ISSUE THREAD

**Issue by dulgherucosmin** [dulgherucosmin/cswd-final-project#2]
In the 'contact.html' page, the **first** `section` height should be reduced, as it is only a small section, however this interferes with `index.html`.

**Used for `index.html`**
```css
/* Main */

main section:first-child {
    width: 100%;
    height:100vh;
}
```

**Used for `contact.html`**
```css
/* Contact Page */

main .contact {
    display: flex;
    flex-direction: row;

    justify-content: center;
}
``` 

As you can see, the `index.html` section takes priority, pls fix kisa
